[package]
name = "wasi-cryptography"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
parking_lot = "0.10"
ring = "0.16"
thiserror = "1.0"
wiggle = "0.1"
wiggle-runtime = "0.1"
zeroize = "1.1"
