[package]
name = "wasi-crypto"
version = "0.1.4"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "Experimental implementation of the WASI cryptography APIs"
documentation = "https://docs.rs/wasi-crypto"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "cryptography"]
keywords = ["webassembly", "wasm", "crypto"]
repository = "https://github.com/webassembly/wasi-crypto"

[dependencies]
aes-gcm = "0.10"
anyhow = "1.0"
byteorder = "1.5"
chacha20poly1305 = "0.10"
curve25519-dalek = "4"
derivative = "2.2"
ed25519-dalek = { version = "2", features = ["rand_core"] }
hkdf = "0.12"
hmac = "0.12"
k256 = { version = "0.13", features = ["ecdsa", "std", "pkcs8", "pem"] }
p256 = { version = "0.13", features = ["ecdsa", "std", "pkcs8", "pem"] }
parking_lot = "0.12"
pqcrypto-kyber = { version = "0.8", optional = true }
pqcrypto-traits = { version = "0.3", optional = true }
rand_core = { version = "0.6", features = ["getrandom"] }
rsa = { version = "0.9", features = ["pem", "sha2"] }
sha2 = { version = "0.10", features = ["oid"] }
subtle = "2.6"
thiserror = "2"
wincode = { version = "0.5", features = ["derive"] }
xoodyak = "0.8"
zeroize = { version = "1.8", features = ["zeroize_derive"] }

[features]
default = ["pqcrypto"]
pqcrypto = ["dep:pqcrypto-kyber", "dep:pqcrypto-traits"]

[badges]
maintenance = { status = "experimental" }
